{{- if .Values.vault_settings.gcp_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/access-mode/versions/latest" 
        fileName: "access-mode"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/auth-enabled/versions/latest" 
        fileName: "auth-enabled"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/message-broker-driver/versions/latest" 
        fileName: "message-broker-driver"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-message-broker-connection-string/versions/latest" 
        fileName: "message-broker-connection-string"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/keycloak-certs-endpoint/versions/latest" 
        fileName: "keycloak-certs-endpoint"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_image_preprocess.secretName }}
      type: Opaque
      data:
      - objectName: "access-mode"
        key: access-mode
      - objectName: "auth-enabled"
        key: auth-enabled
      - objectName: "message-broker-connection-string"
        key: message-broker-connection-string
      - objectName: "message-broker-driver"
        key: message-broker-driver
      - objectName: "keycloak-certs-endpoint"
        key: keycloak-certs-endpoint
{{- end }}
