{{- if .Values.vault_settings.hashicorp_vault }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: vault
  secretObjects:
  - data:
    - key: keycloak-certs-endpoint
      objectName: keycloak-certs-endpoint
    - key: access-mode
      objectName: access-mode
    - key: auth-enabled
      objectName: auth-enabled
    - key: message-broker-connection-string
      objectName: message-broker-connection-string
    - key: message-broker-driver
      objectName: message-broker-driver
    secretName: {{ .Values.secrets.deps_image_preprocess.secretName }}
    type: Opaque
  parameters:
    roleName: {{ .Values.csi.roleName }}
    vaultAddress: "https://vault_host"
    vaultNamespace: "vault_namespace"
    vaultSkipTLSVerify: "true"
    #vaultCACertPath: ""
    vaultKubernetesMountPath: {{ .Values.csi.vaultKubernetesMountPath }}
    objects: |
      - objectName: "keycloak-certs-endpoint"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-backend"
        secretKey: "keycloak-certs-endpoint"
      - objectName: "access-mode"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/common-secret"
        secretKey: "access-mode"
      - objectName: "auth-enabled"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/common-secret"
        secretKey: "auth-enabled"
      - objectName: "message-broker-connection-string"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/common-secret"
        secretKey: "message-broker-connection-string"
      - objectName: "message-broker-driver"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/common-secret"
        secretKey: "message-broker-driver"  
{{- end }}

