# Default values for deps-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Secrets declaration
# Precreate them before deploy
# kubectl create secret generic app-secret-key --from-literal=app-secret-key='<APP_SECRET_KEY>'
# kubectl create secret generic api-key --from-literal=api-key='<API_KEY_SECRET>'
# kubectl create secret generic keycloak-certs-endpoint --from-literal=keycloak-certs-endpoint='<https://KEYCLOAK_URL/auth/realms/Test/protocol/openid-connect/certs>'
secrets:
  keycloak_certs_endpoint:
    secretName: keycloak-certs-endpoint
  preprocess_database:
    secretName: preprocess-database
  rabbitmq_password:
    secretName: rabbitmq-password
  security_certs:
    secretName: security-certs
  kafka_secrets:
    secretName: kafka-secrets
  common_secret:
    secretName: common-secret
  deps_image_preprocess:
    secretName: deps-image-preprocess
  telemetry_secrets:
    secretName: telemetry-secrets

helm:
  helm_logs_job_enabled: false

helm_logs_job:
  serviceAccountName: gitlab-ci
  image:
    path: "/base/kubernetes-helm"
    pullPolicy: IfNotPresent
    tag: "0.1.1"

registry: ""
env: ""

image_preprocess:
  replicaCount: 1
  image:
    path: "/deps-dev-x01/deps-image-preprocess"
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: artifactory
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      memory: 4000Mi
    limits:
      memory: 4000Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

image_preprocess_consumer:
  replicaCount: 1
  image:
    path: "/deps-dev-x01/deps-image-preprocess"
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: artifactory
  resources:
    requests:
      memory: 4000Mi
    limits:
      memory: 4000Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

certs_location:
  certs_default_path: "/tmp/ssl"

image_preprocess_settings:
  DEFAULT_PREPROCESSORS: '["rotation", "orientation"]'

  FILE_STORAGE_URL: 'http://file-storage-nginx:8000/api/storage/v1/file'
  UNIFIER_URL: 'http://unifier:8000/api/unifier/v1'

  # Auth
  AUTH_VERIFY_SSL: false
  ADMINS_GROUP: 'deps-admins'

  # RabbitMQ
  RABBITMQ_TLS_ENABLED: false

  # Kafka
  KAFKA_GROUP_ID: image-preprocess
  KAFKA_SECURITY_ENABLED: false
  KAFKA_ENABLE_AUTO_COMMIT: false
  KAFKA_ENABLE_AUTO_OFFSET_STORE: True
  KAFKA_MAX_POLL_INTERVAL_MS: 300000

  # Azure Service Bus
  ASB_SUBSCRIPTION_STRATEGY: 'no_preparation'
  ASB_TOPIC_NAME: 'deps-topic'
  message_broker_asb_without_manage_permission: false

  # Telemetry
  INSTRUMENTATION_ENABLED: false
  SERVICE_NAME: deps-image-preprocess
  EXPORTER_TYPE: azure

csi:
  csi_default_name: deps-image-preprocess
  vault_namespace: 'k8s-dev'
  roleName: 'k8s-dev'
  vaultKubernetesMountPath: 'kubernetes-dev'

secrets_location:
  secrets_default_path: "/mnt/secrets-store"

service_account:
  serviceAccountName: 'deps-develop'

azure_kv_settings:
  keyvaultName: ""
  tenantId: ""
  userAssignedIdentityID: ""
  resourceGroup: ""
  subscriptionId: ""

vault_settings:
  enabled: false
  hashicorp_vault: false
  azure_key_vault: false
  gcp_secret_manager: false
  aws_secret_manager: false
  aws_secret_manager_region: ''

vault_enabled:
  env:
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: deps-image-preprocess
        key: keycloak-certs-endpoint
  - name: AUTH_ENABLED
    valueFrom:
      secretKeyRef:
        name: deps-image-preprocess
        key: auth-enabled
  - name: ACCESS_MODE
    valueFrom:
      secretKeyRef:
        name: deps-image-preprocess
        key: access-mode
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: deps-image-preprocess
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: deps-image-preprocess
        key: message-broker-connection-string

vault_disabled:
  env:
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: keycloak-certs-endpoint
        key: keycloak-certs-endpoint
  - name: AUTH_ENABLED
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: auth-enabled
  - name: ACCESS_MODE
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: access-mode
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-connection-string

vault_enabled_consumer:
  env:
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: deps-image-preprocess
        key: keycloak-certs-endpoint
  - name: AUTH_ENABLED
    valueFrom:
      secretKeyRef:
        name: deps-image-preprocess
        key: auth-enabled
  - name: ACCESS_MODE
    valueFrom:
      secretKeyRef:
        name: deps-image-preprocess
        key: access-mode
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: deps-image-preprocess
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: deps-image-preprocess
        key: message-broker-connection-string

vault_disabled_consumer:
  env:
  - name: AUTH_CERTS_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: keycloak-certs-endpoint
        key: keycloak-certs-endpoint
  - name: AUTH_ENABLED
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: auth-enabled
  - name: ACCESS_MODE
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: access-mode
  - name: MESSAGING_DRIVER
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-driver
  - name: MESSAGE_BROKER_CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: common-secret
        key: message-broker-connection-string
