apiVersion: v1
kind: ConfigMap
metadata:
  name: image-preprocess-configmap
  labels:
    {{- include "image-preprocess.labels" . | nindent 4 }}
data:
  DEFAULT_PREPROCESSORS: '{{ .Values.image_preprocess_settings.DEFAULT_PREPROCESSORS }}'
  FILE_STORAGE_URL: '{{ .Values.image_preprocess_settings.FILE_STORAGE_URL }}'
  UNIFIER_URL: '{{ .Values.image_preprocess_settings.UNIFIER_URL }}'
  AUTH_VERIFY_SSL: '{{ .Values.image_preprocess_settings.AUTH_VERIFY_SSL }}'
  ADMINS_GROUP: '{{ .Values.image_preprocess_settings.ADMINS_GROUP }}'
  KAFKA_GROUP_ID: '{{ .Values.image_preprocess_settings.KAFKA_GROUP_ID }}'
  KAFKA_ENABLE_AUTO_COMMIT: '{{ .Values.image_preprocess_settings.KAFKA_ENABLE_AUTO_COMMIT }}'
  KAFKA_ENABLE_AUTO_OFFSET_STORE: '{{ .Values.image_preprocess_settings.KAFKA_ENABLE_AUTO_OFFSET_STORE }}'
  KAFKA_MAX_POLL_INTERVAL_MS: '{{ .Values.image_preprocess_settings.KAFKA_MAX_POLL_INTERVAL_MS }}'
  {{ if .Values.image_preprocess_settings.KAFKA_SECURITY_ENABLED }}
  KAFKA_SASL_MECHANISM: '{{ .Values.image_preprocess_settings.KAFKA_SASL_MECHANISM }}'
  KAFKA_SECURITY_PROTOCOL: '{{ .Values.image_preprocess_settings.KAFKA_SECURITY_PROTOCOL }}'
  {{ end }}
  {{ if .Values.image_preprocess_settings.RABBITMQ_TLS_ENABLED }}
  RABBITMQ_TLS_HOST: '{{ .Values.image_preprocess_settings.RABBITMQ_TLS_HOST }}'
  RABBITMQ_TLS_PORT: '{{ .Values.image_preprocess_settings.RABBITMQ_TLS_PORT }}'
  RABBITMQ_TLS_USER: '{{ .Values.image_preprocess_settings.RABBITMQ_TLS_USER }}'
  RABBITMQ_TLS_VHOST: '{{ .Values.image_preprocess_settings.RABBITMQ_TLS_VHOST }}'
  RABBITMQ_TLS_SUBJECT: '{{ .Values.image_preprocess_settings.RABBITMQ_TLS_SUBJECT }}'
  RABBITMQ_TLS_CA_CERT: '{{ .Values.image_preprocess_settings.RABBITMQ_TLS_CA_CERT }}'
  RABBITMQ_TLS_CLIENT_CERT: '{{ .Values.image_preprocess_settings.RABBITMQ_TLS_CLIENT_CERT }}'
  RABBITMQ_TLS_CLIENT_KEY: '{{ .Values.image_preprocess_settings.RABBITMQ_TLS_CLIENT_KEY }}'
  {{ end }}
  {{ if .Values.image_preprocess_settings.message_broker_asb_without_manage_permission }}
  ASB_SUBSCRIPTION_STRATEGY: '{{ .Values.image_preprocess_settings.ASB_SUBSCRIPTION_STRATEGY }}'
  {{ end }}
  ASB_TOPIC_NAME: '{{ .Values.image_preprocess_settings.ASB_TOPIC_NAME }}'
  # Telemetry
  INSTRUMENTATION_ENABLED: '{{ .Values.image_preprocess_settings.INSTRUMENTATION_ENABLED }}'
  SERVICE_NAME: '{{ .Values.image_preprocess_settings.SERVICE_NAME }}'
  EXPORTER_TYPE: '{{ .Values.image_preprocess_settings.EXPORTER_TYPE }}'
