image_preprocess:
  image:
    path: "/deps-platform/deps-image-preprocess"
  resources: {}
    #requests:
    #  memory:
    #limits:
    #  memory:

image_preprocess_consumer:
  image:
    path: "/deps-platform/deps-image-preprocess"
  resources: {}
    #requests:
    #  memory:
    #limits:
    #  memory:

image_preprocess_settings:
  DEFAULT_PREPROCESSORS: '["rotation", "orientation"]'

  # Telemetry
  INSTRUMENTATION_ENABLED: true

helm:
  helm_logs_job_enabled: false

csi:
  vault_namespace: 'k8s-qa'
  roleName: 'k8s-qa'
  vaultKubernetesMountPath: 'kubernetes-qa'

service_account:
  serviceAccountName: 'deps-qa'
