image_preprocess:
  image:
    path: "/deps-platform/deps-image-preprocess"
  resources: {}

image_preprocess_consumer:
  image:
    path: "/deps-platform/deps-image-preprocess"
  resources: {}

image_preprocess_settings:
  DEFAULT_PREPROCESSORS: '["rotation", "orientation"]'

helm:
  helm_logs_job_enabled: false

csi:
  vault_namespace: 'k8s-staging'
  roleName: 'k8s-staging'
  vaultKubernetesMountPath: 'kubernetes-staging'

service_account:
  serviceAccountName: 'deps-staging'
